
# Nome do executável
EXEC = lista

# Compilador
CXX = g++

# Opções de compilação
CXXFLAGS = -Wall -g

# Arquivo fonte
SRC = lista_sequencial.cpp

# Regra padrão
all:
	$(CXX) $(CXXFLAGS) $(SRC) -o $(EXEC)

# Regra para limpar o executável
clean:
	rm -f $(EXEC)
